name: C/C++ CI

on:
  pull_request:

jobs:
  Check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Clippy
      run: |
          git submodule update --init --recursive
          chmod +x ./install_client.sh
          chmod +x ./docker/image/install_deps.sh
          chmod +x ./client/install.py
          bash ./docker/image/install_deps.sh
          echo "Y" | bash ./install_client.sh

    - name: Run Cmake
      run: |
          ./client/bin/clippy cmake

    - name: Run clang-format && clang-tidy
      run: |
            git fetch origin master:refs/remotes/origin/master
            LIST_CHECK_FILES=$(git diff --name-only origin/master | grep '\.cpp\|\.h\|\.hpp' | head -n 1)
            echo ${LIST_CHECK_FILES[@]}
            CUR_DIR=$(pwd)
            for file in ${LIST_CHECK_FILES[@]}
            do
              echo $(dirname $file)
              cd $(dirname $file)
            done
            $CUR_DIR/client/bin/clippy validate

    - name: Run tests
      run: |
            git fetch origin master:refs/remotes/origin/master
            LIST_CHECK_FILES=$(git diff --name-only origin/master | grep '\.cpp\|\.h\|\.hpp' | head -n 1)
            echo ${LIST_CHECK_FILES[@]}
            CUR_DIR=$(pwd)
            for file in ${LIST_CHECK_FILES[@]}
            do
              cd $(dirname $file)
            done
            $CUR_DIR/client/bin/clippy test

