name: C/C++ CI

on:
  pull_request:

jobs:
  Check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Clippy
      run: |
          chmod +x ./install_client.sh
          ./install_client.sh

    - name: Run Cmake
      run: |
          clippy cmake --clean

    - name: Run clang-format && clang-tidy
      run: |
            [[ -z "${GITHUB_BASE_REF}" ]] && BRANCH_VAR=HEAD~1 || BRANCH_VAR=master
            LIST_CHECK_FILES=$(git diff --name-only ${BRANCH_VAR} | grep '\.cpp\|\.h\|\.hpp' | head -n 1)
            echo ${LIST_CHECK_FILES[@]}
            DIR=$(dirname LIST_CHECK_FILES[@])
            cd $(DIR)
            clippy validate

    - name: Run tests
      run: |
        [[ -z "${GITHUB_BASE_REF}" ]] && BRANCH_VAR=HEAD~1 || BRANCH_VAR=master
        LIST_CHECK_FILES=$(git diff --name-only ${BRANCH_VAR} | grep '\.cpp\|\.h\|\.hpp' | head -n 1)
        echo ${LIST_CHECK_FILES[@]}
        DIR=$(dirname LIST_CHECK_FILES[@])
        cd $(DIR)
        clippy test

